version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'root_pass'
            MYSQL_DATABASE: 'contest'
            MYSQL_USER: 'db_user'
            MYSQL_PASSWORD: 'db_user_pass'
